readme: README.md
author: Graham\ Chance
github_url: https://github.com/gtchance/gcactivityindicator
module: GCActivityIndicator
exclude:
  - Tests/*
  - Dependencies/*
xcodebuild_arguments:
    - "-project"
    - "Example/Pods/Pods.xcodeproj"
    - "-scheme"
    - "GCActivityIndicator"